# Import library

In [1]:
import numpy as np
import pandas as pd
import psycopg2 as pg
from datetime import datetime, timedelta
import calendar
import time

# DB connection

In [2]:
conn = pg.connect("dbname=demo user=postgres password=kumden090604")
cur = conn.cursor()

# Get Data

In [19]:
# PYTHON
import requests

def get_data_vn30f1m():
    api = "http://192.168.30.109:8006/api/v1/live?symbol=vn30f1m&start_date=2026-01-22&interval=1m"
    for i in range(5):
        try:
            response = requests.get(api)
            # print(response.json())
            if response.status_code == 200:
                data_json = response.json()
                if data_json["code"] == 200:
                    # Chuyển đổi dữ liệu trả về sang Dataframe
                    flattened_data = [item for batch in data_json["data"] for item in batch]
                    df = pd.DataFrame(flattened_data)
                    return df
                    # print(df)
                    # break
                else:
                    print(data_json["message"])
            else:
                print(response.text)
        except Exception as e:
            print(e)

df_vn30f1m = get_data_vn30f1m()
df_vn30f1m

                 datetime    open    high     low   close  volume       value
0     2026-01-22T09:00:00  2099.1  2101.6  2097.7  2098.5  5098.0  10648702.4
1     2026-01-22T09:01:00  2098.5  2103.6  2098.5  2099.5  2624.0   5483635.2
2     2026-01-22T09:02:00  2099.5  2101.1  2099.1  2100.4  2001.0   4183490.7
3     2026-01-22T09:03:00  2100.7  2102.4  2100.2  2101.0  1307.0   2733329.1
4     2026-01-22T09:04:00  2101.0  2102.5  2100.8  2102.5   939.0   1965139.2
...                   ...     ...     ...     ...     ...     ...         ...
4750  2026-02-25T14:25:00  2051.1  2051.9  2050.5  2051.2  1103.0   2262473.6
4751  2026-02-25T14:26:00  2051.4  2051.5  2050.8  2051.1   525.0   1076827.5
4752  2026-02-25T14:27:00  2051.1  2051.3  2049.2  2050.6   627.0   1285726.2
4753  2026-02-25T14:28:00  2050.5  2051.3  2050.0  2051.1   755.0   1548580.5
4754  2026-02-25T14:29:00  2051.3  2052.0  2050.9  2051.6  1364.0   2798382.4

[4755 rows x 7 columns]

# Make a copy of the original data

In [45]:
dummy = df_vn30f1m.copy()

# Alter data for testing

In [46]:
dummy.loc[3,'datetime'] = '2026-01-23T19:45:00'
dummy.loc[4,'high'] = np.nan
dummy = dummy.drop(2)
new = {"datetime":"2026-09-02T13:20:00", "open": 67,"high": 67,"low": 67,"close":67,"volume": 67,"value":67}
dummy.loc[len(dummy)] = new
dummy

                 datetime    open    high     low   close  volume       value
0     2026-01-22T09:00:00  2099.1  2101.6  2097.7  2098.5  5098.0  10648702.4
1     2026-01-22T09:01:00  2098.5  2103.6  2098.5  2099.5  2624.0   5483635.2
3     2026-01-23T19:45:00  2100.7  2102.4  2100.2  2101.0  1307.0   2733329.1
4     2026-01-22T09:04:00  2101.0     NaN  2100.8  2102.5   939.0   1965139.2
5     2026-01-22T09:05:00  2102.5  2103.3  2101.3  2102.3  1638.0   3427678.8
...                   ...     ...     ...     ...     ...     ...         ...
4750  2026-02-25T14:25:00  2051.1  2051.9  2050.5  2051.2  1103.0   2262473.6
4751  2026-02-25T14:26:00  2051.4  2051.5  2050.8  2051.1   525.0   1076827.5
4752  2026-02-25T14:27:00  2051.1  2051.3  2049.2  2050.6   627.0   1285726.2
4753  2026-02-25T14:28:00  2050.5  2051.3  2050.0  2051.1   755.0   1548580.5
4754  2026-09-02T13:20:00    67.0    67.0    67.0    67.0    67.0        67.0

[4754 rows x 7 columns]

# Testing

In [43]:
class DMBase:
        
        # Loại bỏ dữ liệu lặp và điền thêm dữ liệu bị thiếu
        def check_data(
                df: pd.DataFrame, # Bảng lưu trữ thông tin giao dịch
                asset_class_id: str, # Mã giao dịch (vn3f1m, FPT,...)
                interval: int, # Khoảng thời gian giữa các giao dịch 
                offset: str # Đơn vị cho khoảng thời gian giữa các giao dịch 
        )-> pd.DataFrame:
                match offset:
                        case 'm' : freg_offset = 'min' # phút
                        case 'd' : freg_offset = 'D'   # ngày
                        case 'M' : freg_offset = 'M'   # tháng
                        case _: raise ValueError(f"Unsupported offset: {offset}")

                query = """
                SELECT session_time_start, session_time_end
                FROM asset ass
                JOIN asset_time ast ON ass.asset_name = ast.asset_name
                WHERE asset_class_id = %s
                """

                cur.execute(query, (asset_class_id,))
                ds = pd.DataFrame(cur.fetchall(), columns=[c[0] for c in cur.description])
                df['datetime'] = pd.to_datetime(df['datetime'])
                df['datetime'].dt.strftime("%Y-%m-%d %H:%M:%S")

                sessions = ds[['session_time_start', 'session_time_end']].apply(pd.to_datetime)
                
                query = """
                SELECT holiday_date_start,holiday_date_end
                FROM holiday_calendar
                WHERE asset_class_id = %s
                """
                cur.execute(query, (asset_class_id,))
                dz = pd.DataFrame(cur.fetchall(), columns=[c[0] for c in cur.description])

                dz['holiday_date_start'] = pd.to_datetime(dz['holiday_date_start'])
                holiday_dates = set(dz['holiday_date_start'].dt.date)

                # Loại bỏ những ngày lễ
                df = df[
                ~df['datetime'].dt.date.isin(holiday_dates)
                ]
                start_date = df['datetime'].dt.normalize().min()
                end_date   = df['datetime'].dt.normalize().max()
                # Lưu lại những ngày có thể có giao dịch
                all_days = [
                day for day in pd.date_range(start=start_date, end=end_date, freq='D')
                if day.date() not in holiday_dates
                ]

                full_index = []
                # Lưu lại khung thời gian giao dịch của mỗi ngày
                for day in all_days:
                        # Session 1
                        s1_start = day + pd.Timedelta(
                                hours=sessions.loc[0, 'session_time_start'].hour,
                                minutes=sessions.loc[0, 'session_time_start'].minute
                        )
                        s1_end = day + pd.Timedelta(
                                hours=sessions.loc[0, 'session_time_end'].hour,
                                minutes=sessions.loc[0, 'session_time_end'].minute
                        )

                        # Session 2
                        s2_start = day + pd.Timedelta(
                                hours=sessions.loc[1, 'session_time_start'].hour,
                                minutes=sessions.loc[1, 'session_time_start'].minute
                        )
                        s2_end = day + pd.Timedelta(
                                hours=sessions.loc[1, 'session_time_end'].hour,
                                minutes=sessions.loc[1, 'session_time_end'].minute
                        )
                        
                        full_index.append(pd.date_range(s1_start, s1_end, freq=f'{interval}{freg_offset}'))
                        full_index.append(pd.date_range(s2_start, s2_end, freq=f'{interval}{freg_offset}'))
                
                # Thêm dữ liệu còn thiếu và loại bỏ trùng lặp 
                full_index = pd.concat(
                [pd.Series(idx) for idx in full_index],
                ignore_index=True
                ).sort_values().drop_duplicates()

                full_index = pd.DatetimeIndex(full_index)

                df = dummy.set_index('datetime')
                df = df.reindex(full_index)
                df = df.ffill()

                return df
        
        # Kiểm tra ngày hôm nay có phải ngày nghỉ hay không trong ngày có thể giao dịch không
        @staticmethod
        def is_trading_day(
                asset_class_id: str # Mã giao dịch (vn3f1m, FPT,...)
        )-> bool:
                
                query_days = """
                SELECT distinct days_of_month
                FROM asset ass
                JOIN asset_time ast ON ass.asset_name = ast.asset_name
                WHERE asset_class_id = %s
                """
                query_holiday = """
                SELECT distinct holiday_date_start
                FROM holiday_calendar
                WHERE asset_class_id = %s
                """
                cur.execute(query_days, (asset_class_id,))
                dc = pd.DataFrame(cur.fetchall(), columns=[c[0] for c in cur.description])
                
                cur.execute(query_holiday, (asset_class_id,))
                dz = pd.DataFrame(cur.fetchall(), columns=[c[0] for c in cur.description])
                
                x = datetime.now().weekday()
                y = datetime.now().date()
                x1 = list(map(lambda x1: time.strptime(x1.strip(), "%A").tm_wday, dc.loc[0,"days_of_month"].split(",")))
                if (x in x1):
                        return not bool((dz['holiday_date_start'] == y).any())
                                
                
        # Kiểm tra xem thời gian hiện tại có đang trong thời gian giao dịch 
        @staticmethod
        def is_trading_time(
                asset_class_id: str # Mã giao dịch (vn3f1m, FPT,...)
        )-> bool:
                query = """
                SELECT session_time_start, session_time_end
                FROM asset ass
                JOIN asset_time ast ON ass.asset_name = ast.asset_name
                WHERE asset_class_id = %s
                """

                cur.execute(query, (asset_class_id,))
                ds = pd.DataFrame(cur.fetchall(), columns=[c[0] for c in cur.description])
                sessions = ds[['session_time_start', 'session_time_end']].apply(pd.to_datetime)
                now = datetime.now().time()
                res = any(
                start.time() <= now <= end.time()
                for start, end in zip(sessions.iloc[:, 0], sessions.iloc[:, 1])
                )
                return res

In [44]:
DMBase.check_data(dummy,"vn30f1m",1,'m')

                       open    high     low   close  volume       value
2026-01-22 09:00:00  2099.1  2101.6  2097.7  2098.5  5098.0  10648702.4
2026-01-22 09:01:00  2098.5  2103.6  2098.5  2099.5  2624.0   5483635.2
2026-01-22 09:02:00  2098.5  2103.6  2098.5  2099.5  2624.0   5483635.2
2026-01-22 09:03:00  2098.5  2103.6  2098.5  2099.5  2624.0   5483635.2
2026-01-22 09:04:00  2101.0  2103.6  2100.8  2102.5   939.0   1965139.2
...                     ...     ...     ...     ...     ...         ...
2026-02-25 14:41:00  2050.5  2051.3  2050.0  2051.1   755.0   1548580.5
2026-02-25 14:42:00  2050.5  2051.3  2050.0  2051.1   755.0   1548580.5
2026-02-25 14:43:00  2050.5  2051.3  2050.0  2051.1   755.0   1548580.5
2026-02-25 14:44:00  2050.5  2051.3  2050.0  2051.1   755.0   1548580.5
2026-02-25 14:45:00  2050.5  2051.3  2050.0  2051.1   755.0   1548580.5

[8995 rows x 6 columns]

In [32]:
DMBase.is_trading_day("vn30f1m")

True

In [155]:
DMBase.is_trading_time("vn30f1m")

True

In [243]:
conn.commit()